version: v2beta1

vars:
  RELEASE: local
  NAMESPACE: default

imports:
  - path: ./devspaces/alterconso.yaml
    enabled: true
  - path: ./devspaces/rustfs.yaml
    enabled: true
  - path: ./devspaces/prometheus.yaml
    enabled: false
  - path: ./devspaces/k8up/alterconso.yaml
    enabled: true

pipelines:  
  deploy: |-
    rustfs_install_cli
    alterconso_create_storage_path
    create_deployments alterconso dockerconfigjson
    wait_few_seconds
    alterconso_import_backup
    create_deployments rustfs k8up k8up-backup-secrets
    k8up_install_crds
  backup: |-
    create_deployments k8up-alterconso-podconfig k8up-alterconso-backup
  restore: |-
    create_deployments k8up-alterconso-restore
  purge: |-
    purge_deployments --all
    alterconso_clean_storage_path
    rustfs_clean_pvcs
    k8up_remove_all_resources

hooks:
  - name: "wait-for-rustfs-is-running"
    events: ["after:deploy:rustfs"]
    wait:
      running: true
      terminatedWithCode: 0
    container:
      labelSelector:
        app.kubernetes.io/name: rustfs
  - name: "wait-for-alterconso-database-is-running"
    events: ["after:deploy:alterconso"]
    wait:
      running: true
      terminatedWithCode: 0
    container:
      labelSelector:
        app.kubernetes.io/component: alterconso-database

functions:
  wait_few_seconds: sleep 5
  k8up_install_crds: |-
    kubectl --context local get customresourcedefinition.apiextensions.k8s.io/backups.k8up.io >/dev/null || (
      kubectl --context local apply -f https://github.com/k8up-io/k8up/releases/download/k8up-4.8.6/k8up-crd.yaml --server-side
    )
  k8up_remove_all_resources: |-
    kubectl --context local delete --all backups.k8up.io
    kubectl --context local delete --all restores.k8up.io

deployments:
  k8up:
    helm:
      chart:
        repo: https://k8up-io.github.io/k8up
        name: k8up
        version: 4.8.6
      values:
        k8up: 
          skipWithoutAnnotation: true

  k8up-backup-secrets:
    kubectl:
      inlineManifest: |-
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: k8up
        data:
          AWS_ACCESS_KEY_ID: cnVzdGZzYWRtaW4=
          AWS_SECRET_ACCESS_KEY: cnVzdGZzYWRtaW4=
          RESTIC_PASSWORD: Y2hhbmdlbWU=

commands:
  purge_storage:
    description: Clean up local storage path used for alterconso data persistence
    command: |-
      kubectl --context local delete pvc --all

  purge_cli_tools:
    description: Remove velero and minio CLIs from local machine
    command: |-
      sudo rm -f /usr/local/bin/mc