version: v2beta1

vars:
  RELEASE: local
  NAMESPACE: default
  ALTERCONSO_PATH: ./../alterconso

imports:
  - path: ${ALTERCONSO_PATH}/devspace.yaml
    enabled: true

functions:
  install_k8up_crds: kubectl get backups.k8up.io &>/dev/null || kubectl apply -f https://github.com/k8up-io/k8up/releases/download/k8up-4.8.6/k8up-crd.yaml --server-side

pipelines:
  deploy: |-
    create_deployments --all
    install_k8up_crds

deployments:
  alterconso:
    namespace: ${NAMESPACE}
    helm:
      chart:
        path: ${ALTERCONSO_PATH}/helm
      valuesFiles:
        - ${ALTERCONSO_PATH}/helm/values.yaml
      values:
        webapp:
          image:
            version: dev-latest
        database:
          persistentVolume:
            local:
              path: ${STORAGE_PATH}

  rustfs:
    namespace: ${NAMESPACE}
    helm:
      chart:
        repo: https://rustfs.github.io/helm
        name: rustfs
      values:
        mode:
          standalone:
            enabled: true
          distributed:
            enabled: false
        secret:
          rustfs:
            access_key: rustfsadmin
            secret_key: rustfsadmin
        storageclass:
          name: local-path
        ingress:
          className: ""
          customAnnotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: mkcert
          hosts:
            - host: rustfs.localhost
              paths:
                - path: /
                  pathType: Prefix
          tls:
            enabled: true
            secretName: rustfs.localhost-tls

  k8up:
    helm:
      chart:
        repo: https://k8up-io.github.io/k8up
        name: k8up

  alterconso-backup:
    kubectl:
      inlineManifest: |-
        apiVersion: k8up.io/v1
        kind: Backup
        metadata:
          name: backup-alterconso
        spec:
          failedJobsHistoryLimit: 2
          successfulJobsHistoryLimit: 2
          backend:
            repoPasswordSecretRef:
              name: backup-repo
              key: password
            s3:
              endpoint: http://rustfs-svc.svc.${NAMESPACE}.cluster.local:9000
              bucket: backups
              accessKeyIDSecretRef:
                name: rustfs-secret
                key: RUSTFS_ACCESS_KEY
              secretAccessKeySecretRef:
                name: rustfs-secret
                key: RUSTFS_SECRET_KEY