
image:
  tag: "1.7.11"
loadBalancer: 
  enabled: false
homeWorker:
  probes:
    liveness:
      path: /status?db=1
      initialDelaySeconds: 10
    startup:
      path: /status?db=1
      initialDelaySeconds: 10
docWorker:
  replicas: 1
  useVolume:
    enabled: true
    storageSize: "10Gi"
  probes:
    liveness:
      path: /status?db=1&docWorkerRegistered=1
      initialDelaySeconds: 10
    startup:
      path: /status?db=1&docWorkerRegistered=1
      initialDelaySeconds: 10
ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: mkcert
    traefik.ingress.kubernetes.io/router.middlewares: default-grist-basic-auth@kubernetescrd,default-grist-redirect-to-https@kubernetescrd
  hosts:
    - host: grist.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    additional:
      - secretName: grist.localhost-tls
        hosts:
          - grist.localhost