version: v2beta1

vars:
  NAMESPACE: default

pipelines:  
  deploy: |-
    create_deployments grist-basic-auth-middleware grist-redirect-to-https-middleware
    create_deployments grist

deployments:
  grist-redirect-to-https-middleware:
    kubectl:
      inlineManifest: |-
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: grist-redirect-to-https
        spec:
          redirectRegex:
            regex: "^http://(.*)"
            replacement: "https://$1"
            permanent: true

  grist-basic-auth-middleware:
    kubectl:
      inlineManifest: |-
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: grist-basic-auth
        spec:
          basicAuth:
            secret: grist-basic-auth

  grist:
    helm:
      chart:
        git: https://github.com/gpenaud/helm-charts-dirnum
        subPath: charts/grist
        branch: feature/make-loadbalancer-component-optional
      values:      
        image:
          tag: "1.7.11"
        loadBalancer: 
          enabled: false
        homeWorker:
          probes:
            liveness:
              path: /status?db=1
              initialDelaySeconds: 10
            startup:
              path: /status?db=1
              initialDelaySeconds: 10
        docWorker:
          replicas: 1
          useVolume:
            enabled: true
            storageSize: "10Gi"
          probes:
            liveness:
              path: /status?db=1&docWorkerRegistered=1
              initialDelaySeconds: 10
            startup:
              path: /status?db=1&docWorkerRegistered=1
              initialDelaySeconds: 10
        ingress:
          enabled: true
          className: traefik
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: mkcert
            traefik.ingress.kubernetes.io/router.middlewares: default-grist-basic-auth@kubernetescrd,default-grist-redirect-to-https@kubernetescrd
          hosts:
            - host: grist.localhost
              paths:
                - path: /
                  pathType: Prefix
          tls:
            enabled: true
            additional:
              - secretName: grist.localhost-tls
                hosts:
                  - grist.localhost